import type { Metadata } from "next";
import "./ui/globals.css";
import ScrollSaver from "./componentes/site/scroll-saver";
import FontPreloader from "./componentes/site/font-preloader";


export const metadata: Metadata = {
  title: "Transvium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontPreloader/>
      </head>
      <body
      className=''
      >
        <ScrollSaver/>
        {children}
      </body>
    </html>
  );
}
